BYE_DICT = {
        'Commanders' : 14,
        'Buccaneers' : 11,
        'Seahawks' : 10,
        '49ers' : 9,
        'Chargers' : 5,
        'Steelers' : 9,
        'Cardinals' : 11,
        'Eagles' : 5,
        'Jets' : 12,
        'Giants' : 11,
        'Saints' : 12,
        'Patriots' : 14,
        'Vikings' : 6,
        'Dolphins' : 6,
        'Raiders' : 10,
        'Rams' : 6,
        'Chiefs' : 6,
        'Jaguars' : 12,
        'Colts' : 14,
        'Texans' : 14,
        'Titans' : 5,
        'Packers' : 10,
        'Lions' : 5,
        'Broncos' : 14,
        'Cowboys' : 7,
        'Browns' : 10,
        'Bengals' : 12,
        'Bears' : 7,
        'Panthers' : 11,
        'Bills' : 13,
        'Ravens' : 14,
        'Falcons' : 12
        }

TEAM_DICT = {'TB' : 'Buccaneers',
             'SEA' : 'Seahawks',
             'SF' : '49ers',
             'LAC' : 'Chargers',
             'PIT' : 'Steelers',
             'ARI' : 'Cardinals',
             'PHI' : 'Eagles',
             'NYJ' : 'Jets',
             'NYG' : 'Giants',
             'NO' : 'Saints',
             'NE' : 'Patriots',
             'MIN' : 'Vikings',
             'MIA' : 'Dolphins',
             'LV' : 'Raiders',
             'LAR' : 'Rams',
             'KC' : 'Chiefs',
             'JAX' : 'Jaguars',
             'IND' : 'Colts',
             'TEN' : 'Titans',
             'GB' : 'Packers',
             'DET' : 'Lions',
             'DEN' : 'Broncos',
             'DAL' : 'Cowboys',
             'CLE' : 'Browns',
             'CIN' : 'Bengals',
             'CHI' : 'Bears',
             'CAR' : 'Panthers',
             'BUF' : 'Bills',
             'BAL' : 'Ravens',
             'ATL' : 'Falcons',
             'WAS' : 'Commanders',
             'HOU' : 'Texans'
    }

CITY_TO_TEAM = {
             'Tampa Bay' : 'Buccaneers',
             'Seattle' : 'Seahawks',
             'San Francisco' : '49ers',
             'LA Chargers' : 'Chargers',
             'Pittsburgh' : 'Steelers',
             'Arizona' : 'Cardinals',
             'Philadelphia' : 'Eagles',
             'NY Jets' : 'Jets',
             'NY Giants' : 'Giants',
             'New Orleans' : 'Saints',
             'New England' : 'Patriots',
             'Minnesota' : 'Vikings',
             'Miami' : 'Dolphins',
             'Las Vegas' : 'Raiders',
             'LA Rams' : 'Rams',
             'Kansas City' : 'Chiefs',
             'Jacksonville' : 'Jaguars',
             'Indianapolis' : 'Colts',
             'Tennessee' : 'Titans',
             'Green Bay' : 'Packers',
             'Detroit' : 'Lions',
             'Denver' : 'Broncos',
             'Dallas' : 'Cowboys',
             'Cleveland' : 'Browns',
             'Cincinnati' : 'Bengals',
             'Chicago' : 'Bears',
             'Carolina' : 'Panthers',
             'Buffalo' : 'Bills',
             'Baltimore' : 'Ravens',
             'Atlanta' : 'Falcons',
             'Washington' : 'Commanders',
             'Houston' : 'Texans'
}